(deftheme my
  "Created 2016-02-15.")

(custom-theme-set-faces
 'my
 '(cursor ((((class color) (min-colors 89)) (:background "#204a87"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#204a87"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#babdb6"))))
 '(region ((((class color) (min-colors 89)) (:background "#babdb6"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#8cc4ff"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ef2929"))))
 '(whitespace-line ((t (:background "grey90" :foreground "dark orange"))))
 '(whitespace-indentation ((t (:background "LightYellow" :foreground "dark orange"))))
 '(font-lock-builtin-face ((t (:foreground "#204a87"))))
 '(font-lock-comment-face ((t (:foreground "black" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#5c3566"))))
 '(font-lock-doc-face ((t nil)))
 '(font-lock-function-name-face ((t nil)))
 '(font-lock-keyword-face ((t (:foreground "#204a87"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t nil)))
 '(font-lock-regexp-grouping-construct ((t nil)))
 '(font-lock-string-face ((t (:foreground "#5c3566"))))
 '(font-lock-type-face ((t nil)))
 '(font-lock-variable-name-face ((t nil)))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#204a87"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#3465a4"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#d3d7cf"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "#d3d7cf" :foreground "#2e3436"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "#888a85" :foreground "#2e3436"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ce5c00"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#e9b96e"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(error ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ce5c00"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#4e9a06"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#2e3436" :background "#eeeeec")))))

(provide-theme 'my)
